### ISSUE TITLE
Is it possible to detect private package variable reassignments?

### ISSUE THREAD

**Issue by torkelrogstad** [curioswitch/go-reassign#16]
I want to detect reassignments to a specific, private variable name across multiple packages. Is this possible using this linter?

Some context: across a bunch of different packages I have a variable named `log`, set up like this: 

```go
var log = createLogger("mySubSystem")

func doTheThing() {
  log.Printf("I'm doing the thing")

  // error!
  log = createLogger("somethingElse")
  
  // this is OK, as it doesn't reassign to the package variable
  log := createLogger("foobar")
}
```

I want to avoid that the package scoped variable is reassigned.

**Comment by chokoswitch** [comment]
Hi @torkelrogstad - the current linter code is designed specifically to target imported packages so supporting this would be probably an additional fresh code path. I would need to dig into the linter API to be sure, but I think it is doable for reassignment in a single file as in your example. However, it would be a large effort and slow the linter down to support it across multiple files in a package I think - at the least, it would need to become a multipass linter to collect package variable definitions and then reexamine assignment statements.

Private variables haven't ever really been a focus for this linter because you always have control of the code, where as you don't have control when imported elsewhere - the linter helps making sure this fact doesn't leak into public API, e.g. without the validation there was a trend to constant error pattern vs Golang native errors.

I think implementing for a single file could still be doable, but wouldn't be precise due to missing misuse across multiple files. But multiple files I think would be just too much of a change to the linter's lifecycle. So it feels like a bit too much for this linter and lean towards not adding support - what do you think @torkelrogstad?

**Comment by torkelrogstad** [comment]
Thanks for the additional context in your reply. I think it sounds reasonable to not support this in the linter, as it sounds like it's rather different than what's currently here.

**Comment by chokoswitch** [comment]
Thanks for understanding @torkelrogstad!
